//! The reference all-box building pack from blast-stress-solver.
//!
//! `high-rise-3f-local.json` is generated by
//! /root/workspace/blast-stress-solver/blast/blast-stress-solver/scripts/export-high-rise.mjs
//! (`HIGH_RISE_FLOORS=3`). Unlike `fractured-tower.json` — a Voronoi fracture
//! whose pieces are irregular convex polyhedra — every chunk here is an
//! axis-aligned box, so the rendered box IS the collider. That is the property
//! this file exists to protect: no AABB-vs-hull divergence, and therefore no
//! visual interpenetration between neighbouring chunks.

use std::path::PathBuf;

use vibe_land_destruction::city::{build_city_scene, CitySceneDesc};
use vibe_land_destruction::manifest::DestructionManifest;
use vibe_land_destruction::scene_pack::{load_scene_pack_file, SceneCollider, ScenePack};
use vibe_land_destruction::variants::{make_building_variants, truncate_to_floors, MAXIMUM_FLOORS};

fn pack() -> ScenePack {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("assets/scenes/high-rise-3f-local.json");
    load_scene_pack_file(&path).expect("high-rise-3f-local.json should parse as ScenePack v1")
}

#[test]
fn every_chunk_is_a_box() {
    let pack = pack();
    let hulls = pack
        .node_colliders
        .iter()
        .filter(|c| matches!(c, SceneCollider::ConvexHull { .. }))
        .count();
    assert_eq!(
        hulls, 0,
        "the reference pack must be all cuboids; {hulls} convex hulls found"
    );
    assert_eq!(pack.node_colliders.len(), pack.nodes.len());
}

/// The renderer draws `node_sizes`; physics cooks `node_colliders`. For a box
/// pack these must describe the same solid, or the visuals drift from the sim.
#[test]
fn drawn_size_equals_collider_extent() {
    let pack = pack();
    for (index, collider) in pack.node_colliders.iter().enumerate() {
        let SceneCollider::Cuboid { half_extents } = collider else {
            panic!("node {index} is not a cuboid");
        };
        let size = pack.node_sizes[index];
        let delta = (*half_extents * 2.0 - size).abs();
        assert!(
            delta.max_element() < 1e-4,
            "node {index}: drawn size {size:?} != collider extent {:?}",
            *half_extents * 2.0
        );
    }
}

/// Axis-aligned boxes at rest must tile, not interpenetrate. Face contact is
/// expected (that is what a bond is); shared *volume* is not.
#[test]
fn chunk_boxes_do_not_interpenetrate() {
    let pack = pack();
    let boxes: Vec<(glam::Vec3, glam::Vec3)> = pack
        .nodes
        .iter()
        .zip(&pack.node_colliders)
        .map(|(node, collider)| {
            let SceneCollider::Cuboid { half_extents } = collider else {
                panic!("expected cuboid");
            };
            (node.centroid - *half_extents, node.centroid + *half_extents)
        })
        .collect();

    // Depth, not volume, is the physically meaningful quantity: a wide, paper
    // thin sliver of shared volume between two face-touching slabs is float
    // noise, while a deep overlap of any area is a real modelling error that
    // PhysX would try to push apart.
    let mut worst_depth = 0.0f32;
    let mut worst_pair = (0usize, 0usize);
    for i in 0..boxes.len() {
        for j in (i + 1)..boxes.len() {
            let low = boxes[i].0.max(boxes[j].0);
            let high = boxes[i].1.min(boxes[j].1);
            let extent = (high - low).max(glam::Vec3::ZERO);
            if extent.min_element() > worst_depth {
                worst_depth = extent.min_element();
                worst_pair = (i, j);
            }
        }
    }
    // The exporter rounds coordinates, which leaves ~10 um seams. PhysX runs a
    // 10 mm contact offset, so anything under 0.1 mm cannot produce a
    // depenetration impulse.
    assert!(
        worst_depth < 1.0e-4,
        "chunks {worst_pair:?} interpenetrate by {worst_depth} m; the pack should tile"
    );
}

/// The pack carries the concrete band the stress solver is calibrated for;
/// the server should read it rather than hardcoding limits.
#[test]
fn pack_carries_its_own_stress_limits() {
    let limits = pack().stress_limits.expect("high-rise pack declares limits");
    assert_eq!(limits.compression_elastic, 12.0e6);
    assert_eq!(limits.compression_fatal, 30.0e6);
    assert_eq!(limits.tension_elastic, 1.2e6);
    assert_eq!(limits.tension_fatal, 3.0e6);
    assert_eq!(limits.shear_elastic, 1.6e6);
    assert_eq!(limits.shear_fatal, 4.0e6);
}

/// Floor truncation must produce real, still-supported structures.
#[test]
fn variant_ladder_stays_supported() {
    let source = pack();
    assert_eq!(source.nodes.len(), 318);
    assert_eq!(source.bonds.len(), 1083);
    assert_eq!(source.support_node_count(), 12);

    let expected = [(1u32, 84usize, 206usize), (2, 186, 569), (3, 318, 1083)];
    for (floors, nodes, bonds) in expected {
        let variant = truncate_to_floors(&source, floors, MAXIMUM_FLOORS)
            .unwrap_or_else(|error| panic!("{floors}-floor truncation failed: {error}"));
        assert_eq!(variant.nodes.len(), nodes, "{floors}-floor node count");
        assert_eq!(variant.bonds.len(), bonds, "{floors}-floor bond count");
        assert_eq!(
            variant.support_node_count(),
            12,
            "{floors}-floor must keep its foundation"
        );
    }

    let variants = make_building_variants(&source, true).expect("variant ladder");
    assert_eq!(variants.len(), 3);
}

/// Buildings must not be placed inside each other.
///
/// The reference demo hardcodes `cityPitch = 18 m`, which is correct only for
/// the 8 m-wide fractured tower it ships with. This pack is 18 m wide, so at
/// that pitch neighbouring facades touch: PhysX depenetrates them and the weak
/// infill bonds shear on tick one, demolishing the city before anyone fires.
#[test]
fn city_grid_leaves_a_street_between_buildings() {
    let pack = pack();
    let footprint = vibe_land_destruction::city::pack_footprint_m(&pack);
    assert!(
        footprint > 17.0,
        "expected the ~18 m high-rise footprint, got {footprint}"
    );

    // Ask for the reference's 18 m and require assembly to widen it anyway.
    let scene = build_city_scene(
        &pack,
        CitySceneDesc {
            grid: 4,
            pitch_m: 18.0,
            varied_heights: true,
        },
    )
    .expect("city scene");
    assert!(
        scene.desc.pitch_m >= footprint,
        "pitch {} is narrower than the {footprint} m building footprint",
        scene.desc.pitch_m
    );

    let mut closest = f32::INFINITY;
    for (i, a) in scene.instances.iter().enumerate() {
        for b in &scene.instances[i + 1..] {
            let dx = (a.offset.x - b.offset.x).abs();
            let dz = (a.offset.z - b.offset.z).abs();
            // Axis-aligned footprints: they overlap only if they overlap on both axes.
            let gap = (dx - footprint).max(dz - footprint);
            closest = closest.min(gap);
        }
    }
    assert!(
        closest > 0.0,
        "two buildings overlap: closest face-to-face gap is {closest} m"
    );
}

/// A 4x4 grid of these lands on the ~3k chunk budget the netcode is sized for.
#[test]
fn default_city_fits_the_chunk_budget() {
    let scene = build_city_scene(&pack(), CitySceneDesc::default()).expect("city scene");
    let chunks = scene.total_chunks();
    assert_eq!(scene.instances.len(), 16);
    assert!(
        (2_000..=4_000).contains(&chunks),
        "4x4 high-rise city has {chunks} chunks; expected the ~3k design budget"
    );

    let manifest = DestructionManifest::from_city(&scene);
    assert_eq!(manifest.total_chunks(), chunks);
    // All-box pack => the manifest carries no hull point soup.
    let json = manifest.to_json_bytes();
    assert!(
        json.len() < 2_000_000,
        "all-cuboid manifest should be small, got {} bytes",
        json.len()
    );
}
