import type {ScenarioContract} from './contracts';
export const VEHICLE_QUALITY_SCENARIOS: ScenarioContract[] = [
  {id:'recorded-course',question:'Do correction, trajectory and smoothness budgets hold throughout a captured course?',required:[],responseBudgetTicks:6,status:'replay-ready',capture:'Pinned native Vehicle2 drop, acceleration, steering and braking trace; judge trajectory only.'},
  {id:'garage-fast-heightfield',question:'Does fast driving over the garage washboard and hill crest stay accurate through terrain changes and reconciliation?',required:['heightfield'],responseBudgetTicks:6,status:'replay-ready',capture:'Pinned garage heightfield: sustained 54+ km/h, at least one second at 72+ km/h, washboard, crest and descent. Score vertical, tilt, trajectory and correction errors separately; surface heights do not certify wheel contact or landings.'},
  {id:'idle-slope',question:'Does an idle vehicle remain visually stable on a slope without false ground contact?',required:['clearance','wheels'],responseBudgetTicks:3,status:'needs-native-evidence',capture:'30 s stationary on level and banked surfaces; authoritative wheel travel plus signed collider clearance.'},
  {id:'throttle-release',question:'Does releasing throttle or applying brake stop the old command promptly?',required:['input'],responseBudgetTicks:3,status:'needs-native-evidence',capture:'Sampled command id, accepted input tick, predicted application tick and physical response onset; include quick opposite inputs.'},
  {id:'slalom-grip',question:'Do rapid steering reversals produce correction bursts or visibly wrong orientation?',required:['wheels','input'],responseBudgetTicks:3,status:'needs-native-evidence',capture:'Alternating ±steer, FWD/RWD/AWD, low/high grip, short/long wheelbase; capture four wheel states.'},
  {id:'handbrake-release',question:'Does the handbrake engage and release without lingering braking or ghost traction?',required:['wheels','input'],responseBudgetTicks:3,status:'needs-native-evidence',capture:'Hold/release/reapply handbrake while turning; report axle traction and applied command ids.'},
  {id:'crest-landing',question:'Does the car visibly land once, with correct support, instead of tunnelling then snapping?',required:['landing','clearance','wheels'],responseBudgetTicks:3,status:'needs-native-evidence',capture:'Confirmed takeoff/landing and signed clearance of simple colliders, including roof-first landing.'},
  {id:'bridge-gap',question:'Does the predictor respect a real gap instead of inventing a floor?',required:['clearance','wheels'],responseBudgetTicks:3,status:'needs-native-evidence',capture:'Bridge with empty space below, underpass and sloping edge; oracle clearance comes from full geometry queries.'},
  {id:'wall-glance',question:'Does a high-speed glancing impact slide in the right direction without passing through?',required:['impact','clearance'],responseBudgetTicks:3,status:'needs-native-evidence',capture:'Confirmed contact pair and impulse; angled wall, front bumper and side hits.'},
  {id:'crossing-vehicles',question:'Can two predicted cars collide consistently despite asymmetric link conditions?',required:['impact','clearance'],responseBudgetTicks:6,status:'needs-native-evidence',capture:'Two drivers plus observer, perpendicular and head-on courses; same-tick dynamic actor oracle for both clients.'},
  {id:'cannon-wheel-loss',question:'Does a detached wheel stop generating traction and remain detached after stale packets?',required:['detach','wheels','topology','impact'],responseBudgetTicks:6,status:'needs-native-evidence',capture:'Server-confirmed cannon hit, wheel topology epoch, force per wheel, post-damage steering and surviving rigid islands.'},
  {id:'meteor-wreck',question:'Does catastrophic damage converge to the same wreck without resurrected parts?',required:['topology','impact','wheels'],responseBudgetTicks:12,status:'needs-native-evidence',capture:'Server-confirmed impact, chunk membership epochs, body lifetime ids, missing-wheel functionality; full fracture convergence needs topology-specific oracle.'},
  {id:'outage-recovery',question:'Does control converge after an outage without replaying a long obsolete command burst?',required:['recovery','input'],responseBudgetTicks:12,status:'needs-native-evidence',capture:'Outage during a turn; recovery trigger starts at first usable authority after link restoration, then measure sustained convergence.'},
  {id:'ownership-transfer',question:'Can exit/re-entry or driver transfer apply another driver’s old inputs?',required:['ownership','input'],responseBudgetTicks:3,status:'needs-native-evidence',capture:'Entity generation plus owner epoch; transfer while delayed input/acks from the prior driver remain queued.'},
  {id:'late-join-damaged',question:'Does a late observer see the correct damaged vehicle and current wheel functionality?',required:['topology','wheels'],responseBudgetTicks:12,status:'needs-native-evidence',capture:'Late join and interest-region exit/re-entry after wheel destruction; bootstrap/topology hashes and post-bootstrap poses.'},
];
