// GENERATED by client/scripts/build-city-textures.py -- do not edit.
//
// Layer index is the array layer in city-albedo.webp / city-surface.webp.
// Walls come first, then floors; `cityTextures.ts` relies on that order.

export type CityTextureRole = 'wall' | 'floor';

export interface CityTextureSet {
  slug: string;
  role: CityTextureRole;
  /** Real-world extent of one tile, from Poly Haven's own metadata. */
  metresPerTile: number;
}

export const CITY_TEXTURE_SETS: readonly CityTextureSet[] = [
  { slug: 'cracked_concrete_wall', role: 'wall', metresPerTile: 1.000 },
  { slug: 'worn_mossy_plasterwall', role: 'wall', metresPerTile: 1.800 },
  { slug: 'cracked_concrete_02', role: 'wall', metresPerTile: 2.230 },
  { slug: 'concrete_layers_02', role: 'wall', metresPerTile: 2.000 },
  { slug: 'concrete_floor_worn_02', role: 'floor', metresPerTile: 2.000 },
  { slug: 'concrete_floor_damaged_01', role: 'floor', metresPerTile: 5.000 },
];

export const CITY_ALBEDO_PX = 1024;
export const CITY_SURFACE_PX = 512;
