/**
 * The TypeScript decoder against bytes Rust actually wrote.
 *
 * This is the only test that covers the seam: the Rust suite round-trips its
 * encoder against its own decoder, and nothing on this side has an encoder to
 * round-trip against. A field written in the wrong order, or a section left
 * unaligned, is invisible to both suites and surfaces as a city drawn from
 * scrambled numbers.
 *
 * The fixture is regenerated by the `write_ts_fixture` test in
 * destruction/tests/manifest_binary.rs, which prints the expectations below.
 */
import { readFileSync } from 'fs';
import { fileURLToPath } from 'url';
import path from 'path';
import { describe, expect, it } from 'vitest';

import { decodeBinaryManifest, looksBinary } from './manifestBinary';
import { bondCountOf, bondEndpoints, isConvexHullGeometry, isCuboidGeometry } from './manifest';

const here = path.dirname(fileURLToPath(import.meta.url));
const bytes = readFileSync(path.join(here, '__fixtures__/manifest-rig-column.bin'));
// Copy into a standalone ArrayBuffer: node pools Buffers, so the underlying
// buffer generally has other data before and after, and every offset in the
// decoder is relative to the start of the manifest.
const buffer = bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength);

describe('binary city manifest', () => {
  it('is recognised by its magic', () => {
    expect(looksBinary(buffer)).toBe(true);
    expect(looksBinary(new TextEncoder().encode('{"version":1}').buffer)).toBe(false);
  });

  it('decodes what the Rust encoder wrote', () => {
    const manifest = decodeBinaryManifest(buffer);
    expect(manifest.version).toBe(1);
    expect(manifest.structures).toHaveLength(1);
    const structure = manifest.structures[0];
    expect(structure.chunks).toHaveLength(6);
    expect(bondCountOf(structure)).toBe(10);
    // Values printed by the fixture generator.
    expect(structure.chunks[0].centroid).toEqual([0, -0.5, 0]);
    const { node0, node1 } = bondEndpoints(structure);
    expect(node0[0]).toBe(1);
    expect(node1[0]).toBe(2);
  });

  it('keeps every chunk field finite and self-consistent', () => {
    const structure = decodeBinaryManifest(buffer).structures[0];
    for (const chunk of structure.chunks) {
      expect(Number.isFinite(chunk.mass)).toBe(true);
      expect(Number.isFinite(chunk.volume)).toBe(true);
      expect(chunk.radius).toBeGreaterThan(0);
      expect(chunk.centroid.every(Number.isFinite)).toBe(true);
      expect(chunk.size.every((v) => Number.isFinite(v) && v > 0)).toBe(true);
      // A support chunk is one the solver pins; the rig's footing is one.
      expect(typeof chunk.support).toBe('boolean');
      if (isCuboidGeometry(chunk.geometry)) {
        expect(chunk.geometry.halfExtents.every((v) => v > 0)).toBe(true);
      } else if (isConvexHullGeometry(chunk.geometry)) {
        // Either inline points or a library id, never neither.
        const hasPoints = chunk.geometry.points.length > 0;
        const hasShape = chunk.geometry.shapeId !== undefined;
        expect(hasPoints || hasShape).toBe(true);
        expect(chunk.geometry.points.length % 3).toBe(0);
      }
    }
  });

  it('gives bonds endpoints that exist', () => {
    const structure = decodeBinaryManifest(buffer).structures[0];
    const { node0, node1 } = bondEndpoints(structure);
    expect(node0).toHaveLength(bondCountOf(structure));
    for (let i = 0; i < node0.length; i += 1) {
      expect(node0[i]).toBeLessThan(structure.chunks.length);
      expect(node1[i]).toBeLessThan(structure.chunks.length);
      expect(node0[i]).not.toBe(node1[i]);
    }
  });

  it('does not build bond objects at all', () => {
    // The saving is the point: a city of 190,000 bonds was spending tens of
    // megabytes on objects carrying two 3-vectors nothing reads.
    const structure = decodeBinaryManifest(buffer).structures[0];
    expect(structure.bonds).toBeUndefined();
  });

  it('refuses a format it does not know', () => {
    const wrong = buffer.slice(0);
    new DataView(wrong).setUint32(4, 99, true);
    expect(() => decodeBinaryManifest(wrong)).toThrow(/unsupported/i);
  });
});
